### ISSUE TITLE
add-team-label workflow is missing implementation

### ISSUE THREAD

**Issue by legobeat** [MetaMask/github-tools#24]
The workflow introduced in https://github.com/MetaMask/github-tools/pull/23 is:

- Unnecessarily installing all dependencies and devDependencies (including running installation scripts - unnecessarily exposing a PAT to potentially arbitrary code in the process) for any commit being processed.
- Relying on the repo having a synced `yarn.lock`, and a `package.json` with a `add-team-label` package script

I think it would be very much preferrable if the reusable workflow could carry its own script (vendoring any necessary runtime dependencies)

**Comment by itsyoboieltr** [comment]
I agree that the reusable workflow should carry its own script. I'll work on this improvement 😄
